name: "Snyk Code Scan"

on:
  push:
    branches: [ "main" ]

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Code Scan'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install snyk -g # install snyk
      - run: snyk -v
      - run: snyk auth ${{ secrets.snyk_token }} # snyk authentication using GH secrets
        
      # Run Snyk Code
      - name: Run Snyk Code
        run: |
          snyk test --scan-all-unmanaged
        continue-on-error: true

       # Run Snyk Code
      - name: Run Snyk Code
        run: |
          snyk code test --sarif  > results.sarif
        continue-on-error: true
        
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
    
