name: "Snyk Code Scan"

on:
  push:
    branches: [ "main" ]

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Code Scan'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install snyk -g # install snyk
      - run: snyk -v
      - run: snyk auth ${{ secrets.snyk_token }} # snyk authentication using GH secrets
      
      # Install and Authenticate to Snyk
     # - name: Install Snyk & Authenticate
      #  run: |
       #   sudo npm install -g snyk
        #  snyk auth ${SNYK_TOKEN}
        
      # Run Snyk Code
      - name: Run Snyk Code
        run: |
          snyk test --all-projects
        continue-on-error: true
    
